name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
env:
  AWS_REGION: 'eu-central-1'
permissions:
  id-token: write
  contents: read
  actions: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Sets up NX business
        uses: nrwl/nx-set-shas@v3
      - name: Sets up PNPM and installs dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::210042418509:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: Hello from AWS. STS GetCallerIdentity
        run: |
          aws sts get-caller-identity
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Push the Docker images
        run: pnpx nx run-many -t push-docker-aws --parallel=3
